server:
  error:
    include-message: always
    include-stacktrace: never

spring:
  devtools:
    livereload:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: khamroev
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
        format_sql: true
    show-sql: true
    open-in-view: false
  threads:
    virtual:
      enabled: true