name: CD - Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    patches:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: khamroev
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: customer
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./backend
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest
